### ISSUE TITLE
music analysis tempo is consistently wrong

### ISSUE THREAD

**Issue by jhurlbut** [okio-ai/nendo-platform#46]
I am noticing on some very straightforward dance tracks the tempo calculated by the music analysis plugin is pretty far off from the real tempo

**Comment by faradox** [comment]
This is a limitation of the downstream dependency `essentia`. Since we are not aware of a better tempo detection algorithm available in the open source landscape, we have to close this as "wont fix" for now. If you ever encounter an open source tool that is more precise than essentia's `TempoCNN`, feel free to submit a PR  or otherwise make us aware of it and we'll provide an integration.

**Comment by jhurlbut** [comment]
I see that TempoCNN has a few parameters. Maybe you could expose those in the interface? I know that popular DJ software asks you to set a bpm range for the bpm detect features. I see that TempoCNN has a min/max range parameter. Maybe allowing a user to set those to a range (ie 118-128 for house music) would improve the results?
