### ISSUE TITLE
polymath fails on timeout

### ISSUE THREAD

**Issue by jhurlbut** [okio-ai/nendo-platform#58]
Getting this error on some tracks

Error processing track 32e557bc-1a1e-42ab-8fa3-97dc9e280742: Operation timed out
Traceback (most recent call last): File "/home/nendo/.local/lib/python3.8/site-packages/rq/worker.py", line 1431, in perform_job rv = job.perform() File "/home/nendo/.local/lib/python3.8/site-packages/rq/job.py", line 1280, in perform self._result = self._execute() File "/home/nendo/.local/lib/python3.8/site-packages/rq/job.py", line 1317, in _execute result = self.func(*self.args, **self.kwargs) File "/home/nendo/nendo-server/nendo_server/./handler/nendo_actions_handler.py", line 179, in dockerized_func raise Exception(err_log) Exception: [' stdout = self.stdout.read()', ' File "run.py", line 26, in timeout_handler', ' raise TimeoutError("Operation timed out")', 'TimeoutError: Operation timed out', '']

00:03:15 [Job Polymath_2OJvPz52_0]: exception raised while executing (handler.nendo_actions_handler.dockerized_func)
nendo-server    | Traceback (most recent call last):
nendo-server    |   File "/home/nendo/.local/lib/python3.8/site-packages/rq/worker.py", line 1431, in perform_job
nendo-server    |     rv = job.perform()
nendo-server    |   File "/home/nendo/.local/lib/python3.8/site-packages/rq/job.py", line 1280, in perform
nendo-server    |     self._result = self._execute()
nendo-server    |   File "/home/nendo/.local/lib/python3.8/site-packages/rq/job.py", line 1317, in _execute
nendo-server    |     result = self.func(*self.args, **self.kwargs)
nendo-server    |   File "/home/nendo/nendo-server/nendo_server/./handler/nendo_actions_handler.py", line 179, in dockerized_func
nendo-server    |     raise Exception(err_log)
nendo-server    | Exception: ['    stdout = self.stdout.read()', '  File "run.py", line 26, in timeout_handler', '    raise TimeoutError("Operation timed out")', 'TimeoutError: Operation timed out', '']

**Comment by faradox** [comment]
The large branch I merged today that overhauled the timeout detection includes a fix for your issue of polymath timing out. The timeout is now applied to each step in polymath instead of the entirety of the run and we set it to 10 minutes. Depending on the length of the track and your hardware, you might still run into the timeout occasionally. In this case, you can use the `DEFAULT_TRACK_PROCESSING_TIMEOUT` environment variable to configure the timeout value. Just set it to the desired value in seconds. Mind you that with very long tracks, the stemifier can run out of memory and will never terminate, in this case running into the timeout is desired behavior so the other tracks in the action can still be processed properly instead of the action getting completely stuck like in that other ticket you opened about the music analyzer.
